services:
  
 
  django-web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    container_name: django-docker
    volumes:
      - .:/app
    
    ports:
     - "8000:8000"

# services:
#   web:
#     build: .
#     command: gunicorn --bind 0.0.0.0:8000 my_app.wsgi:application
#     container_name: django-docker
#     volumes:
#       - .:/app
#     ports:
#      - "8000:8000"
#     env_file:
#       - .env